version: 0.0
os: linux
files:
  - source: KickStacker/public/bundle.js
  destination: /home/ec2-user/KickStacker/public
  -source: KickStacker/public/index.html
  destination: /home/ec2-user/KickStacker/public

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root