version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "building"
  build:
    commands:
      - echo "bundling the applictaion"
      - npm run build
      - echo "build is successful"
